stages:
  - test
  
test 1:
  stage: test
  script:
    - CHCP 65001
    - pytest .\my_server\test_server.py -v

test 2:
  stage: test
  script:
    - CHCP 65001
    - pytest .\my_server\test_bots.py -v