stages:
  - test
  
test server:
  stage: test
  script:
    - CHCP 65001
    - pytest .\my_server\test_server.py -v

test bots:
  stage: test
  script:
    - CHCP 65001
    - pytest .\my_server\test_bots.py -v